version: '3.7'
services:
    tinkerqa_bot:
        container_name: tinkerqa_bot
        build:
            context: .
        volumes:
            - ./:/app
        image: tinkerqa-discord:latest
        restart: on-failure